spring.application.name=agentic-ai-system
openai.api.key=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
openai.model=gpt-4o-mini


ollama.base-url=http://localhost:11434
ollama.model-name=qwen3:14b
ollama.chat-model.timeout=PT5M
